<!-- Definition scheme for snippets -->

<!-- Main-Element -->
<!ELEMENT tifo (info, version+)>
    <!ATTLIST tifo
        guid ID #REQUIRED
        isTemplate CDATA #IMPLIED
    >

<!-- General Meta-Information for the snippet -->
<!ELEMENT info (description, structure)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT structure (level*)>
    <!ELEMENT level (#PCDATA)>
    <!ATTLIST level
            number CDATA #REQUIRED>

<!-- Definition of each version of the snippet -->
<!ELEMENT version (content+)>
<!ATTLIST version
 number CDATA #REQUIRED>

<!-- Content Definition for each version and a specific language--> 
<!ELEMENT content ANY>
<!ATTLIST content
    lang (none | de | en) #REQUIRED
    date CDATA #REQUIRED
    transtate (original | pending | translated) #REQUIRED
>

<!-- Target Node for another tifo snippet -->
<!ELEMENT tifotarget (#PCDATA)>
<!ATTLIST tifotarget
    guid ID #REQUIRED
    targetguid ID #IMPLIED
>

<!-- Allowable HTML-Elements -->
<!ELEMENT a ANY>
<!ATTLIST a
    id ID #IMPLIED
    class CDATA #IMPLIED
    href CDATA #REQUIRED
    target (_self | _blank | _parent | _top | _unfencedTop) #IMPLIED
>

<!ELEMENT address ANY>
<!ATTLIST address
    id ID #IMPLIED
    class CDATA #IMPLIED
>

<!ELEMENT aside ANY>
<!ATTLIST aside
    id ID #IMPLIED
    class CDATA #IMPLIED
>

<!ELEMENT body ANY>

<!ELEMENT div ANY>
<!ATTLIST div
    id ID #IMPLIED
    class CDATA #IMPLIED
>

<!ELEMENT footer ANY>
<!ATTLIST footer
    id ID #IMPLIED
    class ID #IMPLIED
>

<!ELEMENT head (meta*, link*, title?)>

<!ELEMENT header ANY>
<!ATTLIST header
    id ID #IMPLIED
    class CDATA #IMPLIED
>

<!ELEMENT html (head, body)>
<!ATTLIST html
    lang CDATA #IMPLIED
>

<!ELEMENT img EMPTY>
<!ATTLIST img
    id ID #IMPLIED
    class CDATA #IMPLIED
    src CDATA #IMPLIED
    alt CDATA #IMPLIED
>

<!ELEMENT link EMPTY>
<!ATTLIST link
    rel CDATA #IMPLIED
    type CDATA #IMPLIED
    href CDATA #IMPLIED
    media CDATA #IMPLIED
>

<!ELEMENT main ANY>
<!ATTLIST main
    id ID #IMPLIED
    class CDATA #IMPLIED
>

<!ELEMENT meta EMPTY>
<!ATTLIST meta
    charset CDATA #IMPLIED
    name CDATA #IMPLIED
    content CDATA #IMPLIED
>

<!ELEMENT nav ANY>
<!ATTLIST nav
    id ID #IMPLIED
    class CDATA #IMPLIED
>

<!ELEMENT p ANY>
<!ATTLIST p
    id ID #IMPLIED
    class CDATA #IMPLIED
>

<!ELEMENT title (#PCDATA)>